# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BVKgE5CQiiD2ldMFgYqUyIZPLbAlGYyZ
"""

import nltk
import codecs
import pandas as pd
nltk.download('words')

english_vocab = set(w.lower() for w in nltk.corpus.words.words())

content = pd.read_csv("distinctwords.csv", sep='\t', engine='python')
content2 = []
counter = 0
for word in content['x']:
  temp = word
  if (temp in english_vocab):
    counter += 1
    
counter