# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MfV-4jMrjhs5phjrbarUOakfbKDZUqZk
"""

import nltk
import codecs
import pandas as pd
nltk.download('words')

english_vocab = set(w.lower() for w in nltk.corpus.words.words())

content = pd.read_csv("mostpopularwords.csv", engine='python')
content

output = pd.DataFrame(columns=['Words', 'Usage'])
for idx, word in enumerate(content.Words):
  temp = word
  if (temp in english_vocab):
    output.loc[idx] =(content.iloc[idx].Words, content.iloc[idx].Usage)
    
output

output.to_csv('MostCommonWords.csv', index=None, header=True)